declare module "#auth-utils" {
  interface User {
    id?: string; // ID is auto generated by the db
    name: string;
    email: string;
    password?: string; // Only used for validation
    role: "admin" | "subscriber" | "author";
    avatarPath?: string | null;
    createdAt: Date;
    updatedAt?: Date; // No update at all is possible
  }

  interface UserSession {
    // Add your own fields
  }

  interface SecureSessionData {
    // Add your own fields
  }
}

export {};
